---
- name: Run RL Experiments
  hosts: localhost
  vars:
    base_command: python evaluate_rl_minigrid.py --algo ppo --use-gae --num-eval-episodes 30
    seeds: [123456, 789012, 345678]
    blip_spp_lambdas: [0.5, 2.0, 4.0]
    blip_spp_lambdas2: [0.5, 2.0]
    blip_ewc_lambdas: [1000.0, 2500.0, 5000.0]
    fisher_terms: ['f0t', 'ft']
    ewc_lambda: 5000.0
    f_prior: 1e-16
    f_prior2: 5e-18
    experiments: "minigrid-redbluedoor-lavagap-doorkey-wallgap"
    tasks_sequences: 1
    initial_prune_percent: [0., 30.]
    scheduler_states: [true, false]
    prune_higher_states: [true, false]
    prune_higher_states2: false 

  tasks:
    - name: "Fine-Tuning EVAL"
      shell: "{{ base_command }} --approach fine-tuning --tasks-sequence {{ tasks_sequences }} --experiment {{ experiments }} --date 2023-10-18 >> eval_log.txt"

    - name: "EWC EVAL"
      shell: "{{ base_command }} --approach ewc --ewc-lambda {{ ewc_lambda }} --tasks-sequence {{ tasks_sequences }} --experiment {{ experiments }} --date 2023-10-20 >> eval_log.txt"

    - name: "BLIP EVAL F-prior {{ f_prior }}"
      shell: "{{ base_command }} --approach blip --F-prior {{ f_prior }} --tasks-sequence {{ tasks_sequences }} --experiment {{ experiments }} --date 2023-10-21 >> eval_log.txt"

    - name: "BLIP+EWC EVAL lamb {{ item[0] }} fisher {{ item[1] }}"
      shell: "{{ base_command }} --approach blip_ewc --ewc-lambda {{ item[0] }} --F-prior {{ f_prior }} --fisher-term {{ item[1] }} --tasks-sequence {{ tasks_sequences }} --experiment {{ experiments }} --date 2023-10-20 >> eval_log.txt"
      with_nested:
        - "{{ blip_ewc_lambdas }}"
        - "{{ fisher_terms }}"     

    - name: "BLIP+SPP EVAL lamb {{ item }}"
      shell: "{{ base_command }} --approach blip_spp --spp-lambda {{ item }} --F-prior {{ f_prior }} --tasks-sequence {{ tasks_sequences }} --experiment {{ experiments }} --date 2023-10-19 >> eval_log.txt"
      with_items: "{{ blip_spp_lambdas }}"

    - name: "BLIP+SPP+MASK EVAL lamb {{ item[0] }} prune {{ item[1] }} scheduler {{ item[2] }} prune_higher {{ item[3] }}"
      shell: >
        {{ base_command }} --approach blip_spp_mask --spp-lambda {{ item[0] }} --F-prior {{ f_prior }} --tasks-sequence {{ tasks_sequences }} --experiment {{ experiments }} --initial-prune-percent {{ item[1] }}
        {{ ' --use-scheduler' if item[2] else '' }}
        {{ ' --prune-higher' if item[3] else '' }}  --date 2023-10-24 >> eval_log.txt
      with_nested:
        - "{{ blip_spp_lambdas }}"
        - "{{ initial_prune_percent }}"
        - "{{ scheduler_states }}"
        - "{{ prune_higher_states }}"

    - name: "BLIP EVAL F-prior {{ f_prior2 }}"
      shell: "{{ base_command }} --approach blip --F-prior {{ f_prior2 }} --tasks-sequence {{ tasks_sequences }} --experiment {{ experiments }} --date 2023-11-06 >> eval_log.txt"

    - name: "BLIP+SPP+MASK EVAL lamb {{ item[0] }} prune {{ item[1] }} scheduler {{ item[2] }} prune_higher {{ prune_higher_states2 }} F-prior {{ f_prior2 }}"
      shell: >
        {{ base_command }} --approach blip_spp_mask --spp-lambda {{ item[0] }} --F-prior {{ f_prior2 }} --tasks-sequence {{ tasks_sequences }} --experiment {{ experiments }} --initial-prune-percent {{ item[1] }}
        {{ ' --use-scheduler' if item[2] else '' }} --date 2023-11-06 >> eval_log.txt
      with_nested:
        - "{{ blip_spp_lambdas2 }}"
        - "{{ initial_prune_percent }}"
        - "{{ scheduler_states }}"