---
- name: Run RL Experiments
  hosts: localhost
  vars:
    base_command: python main_rl_minigrid.py --algo ppo --use-gae --tasks-sequence 3 --experiment minigrid-lavagap-doorkey-emptyrand-redbluedoor-wallgap --num-env-steps 500000 --no-cuda
    seeds: [1, 100, 1000]
    blip_spp_lambdas: [4.0, 0.5, 2.0]
    blip_ewc_lambdas: [5000.0, 2500.0, 1000.0]
    fisher_terms: ['f0t', 'ft']
    ewc_lambda: 5000.0
    f_prior: 1e-16

  tasks:
    - name: "Fine-Tuning seed {{ item }}"
      command: "{{ base_command }} --approach fine-tuning --seed {{ item }}"
      with_items: "{{ seeds }}"

    - name: "BLIP+SPP seed {{ item[0] }} lamb {{ item[1] }}"
      command: "{{ base_command }} --approach blip_spp --seed {{ item[0] }} --spp-lambda {{ item[1] }}"
      with_nested:
        - "{{ seeds }}"
        - "{{ blip_spp_lambdas }}"

    - name: "BLIP+EWC seed {{ item[0] }} lamb {{ item[1] }} fisher {{ item[2] }}"
      command: "{{ base_command }} --approach blip_ewc --seed {{ item[0] }} --ewc-lambda {{ item[1] }} --fisher-term {{ item[2] }}"
      with_nested:
        - "{{ seeds }}"
        - "{{ blip_ewc_lambdas }}"
        - "{{ fisher_terms }}"

    - name: "EWC seed {{ item }}"
      command: "{{ base_command }} --approach ewc --seed {{ item }} --ewc-lambda {{ ewc_lambda }}"
      with_items: "{{ seeds }}"

    - name: "BLIP seed {{ item }}"
      command: "{{ base_command }} --approach blip --seed {{ item }} --F-prior {{ f_prior }}"
      with_items: "{{ seeds }}"
