---
- name: Run Python script
  hosts: localhost
  tasks:
    - name: Execute Python script
      command: python ./evaluate_rl_minigrid.py --algo ppo --approach blip --date 2023-01-18 --experiment minigrid-tb-blip-5e5-doorkey-wallgap-lavagap-redbluedoor --num-eval-episodes 30
      register: script_output
      
    - debug:
      var: script_output.stdout_lines
